service: university-project # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  role: arn:aws:iam::TODO:role/lambda-user

# you can overwrite defaults here
  stage: dev
  region: us-east-1

functions:
  pushToKinesis2:
    handler: handler.pushToKinesis2

  pushToAlgolia2:
    handler: handler.pushToAlgolia2
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:TODO:stream/university-project-stream
          batchSize: 100
          startionPosition: LATEST
          enabled: true
  getMenu:
    handler: handler.getMenu
    events:
      - http:
          cors: true
          path: menu
          method: get
          private: false
  getUniversityById:
    handler: handler.getUniversityById
    events:
      - http:
          cors: true
          path: universities/{id}
          method: get
          private: false
          request:
            parameters:
              path:
                id: false
  search:
    handler: handler.search
    events:
      - http:
          cors: true
          path: universities
          method: get
          private: false
